[package]
name = "gapua-bench"
version = "0.1.0"
authors = ["Sergejs Melderis <sergejs.melderis@sinch.com>"]
edition = "2021"



[dependencies.gaoya]
version = "*"
path = "../gaoya"

[profile.release]
debug = true

[dependencies]
itertools = "0.10.1"
rand = "0.8.4"
rayon = "1.5.1"

