[package]
name = "gaoya"
version = "0.1.0"
authors = ["Sergejs Melderis <sergey.melderis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true


[lib]
name = "gaoya"
path = "src/lib.rs"
bench = false

[dependencies]
rand = "0.8.3"
rand_pcg = "0.3.0"
sha-1 = "0.9.2"
siphasher = "0.3.3"
random_choice = "0.3.2"
fxhash = "0.2.1"
rayon = "1.5.0"
seahash = "4.0.1"
itertools = "0.10.0"
#num = "0.4.0"
num-traits = "0.2.14"
ngram = "0.1.13"
shingles = "0.1.1"



