[build-system]
requires = ["maturin>=0.15"]
build-backend = "maturin"

[project]
name = "gaoya"
requires-python = ">=3.7"
version = "0.1.3"

[package.metadata.maturin]
name = "gaoya"
classifier = [
    "Programming Language :: Rust",
]


