name: Create Python release manylinux

on:
  push:
#    tags:
#      - '*'

jobs:
  build_manylinux:
    name: Create Release manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish wheel
        uses: docker://konstin2/maturin:latest
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          entrypoint: /bin/bash
          args: .github/deploy_manylinux.sh
