name: Create macOs universal2 python release

on: [push, pull_request]

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Setup universal2 targets for Rust
        run: |
          rustup target add aarch64-apple-darwin
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare maturin publish
        shell: bash
        run: |
          cd py-gaoya
          rustup override set stable
      - name: maturin publish
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          maturin-version: 0.12.6
          command: publish
          args: -m py-gaoya/Cargo.toml --no-sdist --universal2 -o wheels -i python -r https://test.pypi.org/legacy/ --username serega
